# Generated by Django 4.2.10 on 2024-03-02 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='product name')),
                ('start_date', models.DateField(null=True, verbose_name='product start date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='cost of product')),
                ('min_students', models.PositiveIntegerField(default=5, verbose_name='minimal number users in group')),
                ('max_students', models.PositiveIntegerField(default=10, verbose_name='maximal number users in group')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='who created')),
            ],
        ),
    ]
